---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: next-9
          standalone: true

      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version-file: ".tool-versions"
          cache: "pnpm"

      - name: pnpm install
        run: pnpm install

      - name: Test
        run: pnpm test
